app/routes.php
<?php
if (in_array(Request::segment(1), Config::get('app.alt_langs'))){
	App::setLocale(Request::segment(1));
	Session::set('la',App::getLocale());
	Config::set('app.locale_prefix', Request::segment(1));
}
$routes = Lang::get('routes');
foreach($routes as $k => $v){
	Route::pattern($k, $v);
}
$la = App::getLocale();
Route::group(array('prefix'=>Config::get('app.locale_prefix'),"before"=>'auth'),function(){
    /*************************************************************************/
    Route::get("/{customer_portal}","HomeController@datasheet");
    Route::post("/customer_portal/data",['as'=>'datasheet.data','uses'=>'HomeController@datasheet_search']);
});
Route::group(array('prefix' =>Config::get('app.locale_prefix')),function(){
	/*************************************************************************/
	Route::get("/{product}","HomeController@product");
	Route::get("/{product}/{title}","HomeController@product_page");
	/*************************************************************************/
	Route::get("/{projects}","HomeController@project");
	Route::get("/{projects}/{title}/","HomeController@project_page");
	/*************************************************************************/
	Route::get("/",['as'=>'home','uses'=>"HomeController@home"]);
	Route::get("/{about}","HomeController@about");
	/*************************************************************************/
	Route::get("/{learning}","HomeController@news");
    Route::get("/{learning}/{category}/{title}","HomeController@news_page");
    Route::get("/{learning}/{category}/","HomeController@news_cat");
    /*************************************************************************/
    Route::get("/{team}/{title}","HomeController@team");
	/*************************************************************************/
	Route::get("/{service}/{category}","HomeController@service");
	Route::get("/{service}/{category}/{title}","HomeController@service_page");

	/*************************************************************************/
    Route::get("/{contact}","HomeController@contact");
});
Route::group(array('prefix'=>"admin",'before'=>'auth'),function(){
	Route::get('dashboard',function(){
        $arr = array();
        foreach (Auth::user()->group as $gp){
            $arr[] = $gp->en_name;
        }
        $user_gp = $arr[0];
        if($user_gp == "admin"){
            return View::make('backend.index')->with('class_dashboard','class="open active"');
        }else{
            return Redirect::route('home');
        }
	});
	/*************************************************************************/
	Route::resource('teams', 'TeamsController');
	Route::resource('team_categories', 	'TeamCategoriesController');
	Route::resource('team_profession_categories', 'TeamProfessionCategoriesController');
	/*************************************************************************/
	Route::resource('menu','MenusController');
	/*************************************************************************/
	Route::resource('portfolio_categories', 'PortfolioCategoriesController');
	Route::resource('portfolios', 'PortfoliosController');
	/*************************************************************************/
	Route::resource('companies', 'CompaniesController');
	Route::resource('company_categories', 'CompanyCategoriesController');
	/*************************************************************************/
	Route::resource('elearnings', 'ElearningsController');
	Route::resource('elearning_categories', 'ElearningCategoriesController');
	Route::resource('medias', 'MediasController');
	/*************************************************************************/
	Route::resource('products', 'ProductsController');
	Route::resource('product_categories', 'ProductCategoriesController');
	/*************************************************************************/
	Route::resource('pages', 'PagesController');
	/*************************************************************************/
	Route::resource('datasheets', 'DatasheetsController');
	Route::resource('datasheet_codes', 'DatasheetCodesController');
	Route::resource('datasheet_companies', 'DatasheetCompaniesController');
	Route::resource('datasheet_project_types', 'DatasheetProjectTypesController');
	Route::resource('datasheet_customers', 'DatasheetCustomersController');
	/*************************************************************************/
	Route::resource('users', 'UserController');
	Route::resource('groups', 'GroupsController');
	/*************************************************************************/
	Route::resource('services', 'ServicesController');
	/*************************************************************************/
	Route::resource('service_categories', 'ServiceCategoriesController');
	Route::resource('settings', 'SettingsController');
	/*************************************************************************/
	Route::resource('sliders', 'SlidersController');
	Route::resource('portfolio_customers', 'PortfolioCustomersController');
});
Route::controller('password', 'RemindersController');
Route::get('login', array('as' => 'login', 'uses' => 'UserController@loginshow'));
Route::post('login', array('as' => 'login', 'uses' => 'UserController@authenticate'));
Route::get('logout', array('as' => 'logout', 'uses' => 'UserController@logout'));
Route::get('sitemap',function(){
    $portfolio = Portfolio::orderBy('created_at')->get();
    $learning = Elearning::orderBy('created_at')->get();
    $service = Service::orderBy('created_at')->get();
    $team = Team::orderBy('created_at')->get();
    $product = Product::orderBy('created_at')->get();
	$sitemap = App::make('sitemap');
    //$sitemap->setCache('laravel.sitemap', 3600);
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale()),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.product',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.certificate',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.mission_statement',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.organizational_value',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.customers',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
    foreach ($product as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($portfolio as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($learning as $l) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale()).'/'.$l->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($service as $s) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.service',array(),App::getLocale()).'/'.$s->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($team as $t) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.team',array(),App::getLocale()).'/'.$t->{App::getLocale().'_family'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }

    return $sitemap->render('xml');
});
App::missing(function(){
	return Response::view('layout.front.404',array('title'=>'not found'),404);
});

app/models/ElearningCategory.php
<?php

class ElearningCategory extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		 'fa_ecat_title' => 'required',
		 //'en_ecat_title' => 'required',
		 //'ru_ecat_title' => 'required',
	];

	// Don't forget to fill this array
	protected $fillable = ['ru_ecat_title','fa_ecat_title','en_ecat_title'];
	public function elearning(){
		return $this->belongsToMany('Elearning');
	}
}

app/controllers/ElearningCategoriesController.php
<?php

class ElearningCategoriesController extends \BaseController {

	/**
	 * Display a listing of elearningcategories
	 *
	 * @return Response
	 */
	public function index()
	{
		$elearningcategories = Elearningcategory::all();
		return View::make('backend.elearning_categories.index', compact('elearningcategories'))
		->with('title','لیست دسته بندی')
        ->with('class_elearning',"class='open active'");
	}

	/**
	 * Show the form for creating a new elearningcategory
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('backend.elearning_categories.create')
		->with('title','ایجاد دسته بندی جدید')
        ->with('class_elearning',"class='open active'");
	}

	/**
	 * Store a newly created elearningcategory in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make($data = Input::all(), Elearningcategory::$rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}
		Elearningcategory::create($data);
		return Redirect::route('admin.elearning_categories.index')
		->with('success','اطلاعات جدید با موفقیت ذخیره شد')
		->with('title','لیست دسته بندی')
		->with('class_elearning','class="active open"');
	}

	/**
	 * Display the specified elearningcategory.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$elearningcategory = Elearningcategory::findOrFail($id);

		return View::make('backend.elearning_categories.show', compact('elearningcategory'));
	}

	/**
	 * Show the form for editing the specified elearningcategory.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$elearningcategory = Elearningcategory::find($id);
		return View::make('backend.elearning_categories.edit', compact('elearningcategory'))
		->with('class_elearning',"class='open active'")
		->with('title',"ویرایش دسته بندی");
	}

	/**
	 * Update the specified elearningcategory in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$elearningcategory = Elearningcategory::findOrFail($id);
		$validator = Validator::make($data = Input::all(), Elearningcategory::$rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}
		$elearningcategory->update($data);
		return Redirect::route('admin.elearning_categories.index')
		->with('class_elearning',"class='open active'")
		->with('update','اطلاعات با موفقیت ویرایش شد');
	}

	/**
	 * Remove the specified elearningcategory from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Elearningcategory::destroy($id);
		return Redirect::route('admin.elearning_categories.index')
		->with('success','اطلاعات مورد نظر با موفقیت حذف شد')
		->with('class_elearning',"class='open active'")
		->with('title','لیست دسته بندی');
	}

}

app/views/backend/elearning_categories/create.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
    {{HTML::style('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css')}}
@stop()
@section('content')
    <div class="col-sm-9">
        @if($errors->has())
            <div class="alert alert-danger ">
                <button data-dismiss="alert" class="close">×</button>
                @foreach($errors->all() as $errors)
                    <i class="fa fa-bug"></i>
                    {{$errors}}<br/>
                @endforeach()
            </div>
        @endif()
    </div>
    <div class="row">
        <div class="col-sm-12">
            <!-- start: TEXT FIELDS PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    {{Form::open(array('route'=>'admin.elearning_categories.store','method'=>'POST','class'=>'form-horizontal','role'=>'form'))}}
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان فارسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('fa_ecat_title','',array( "placeholder"=>"عنوان فارسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان انگلیسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('en_ecat_title','',array( "placeholder"=>"عنوان انگلیسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان روسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('ru_ecat_title','',array( "placeholder"=>"عنوان روسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label"></label>
                        {{Form::submit('ذخیره اطلاعات',array('class'=>'btn btn-primary'))}}
                    </div>
                    {{Form::close()}}
                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>
    </div>
@stop
@section('script')
    @parent()
    {{HTML::script('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js')}}
@stop()

app/views/backend/elearning_categories/edit.blade.php
@extends("layout.admin_index")
@section('style')
    @parent

@stop()
@section('content')
    <div class="col-sm-9">
        @if($errors->has())
            <div class="alert alert-danger ">
                <button data-dismiss="alert" class="close">×</button>
                @foreach($errors->all() as $errors)
                    <i class="fa fa-bug"></i>
                    {{$errors}}<br/>
                @endforeach()
            </div>
        @endif()
    </div>
    <div class="row">
        <div class="col-sm-12">
            <!-- start: TEXT FIELDS PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ Form::model($elearningcategory,array('route'=>array('admin.elearning_categories.update','id'=>$elearningcategory->id),'method'=>'PUT','class'=>'form-horizontal','role'=>'form')) }}
                    {{Form::token()}}
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان فارسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('fa_ecat_title',null,array( "placeholder"=>"عنوان فارسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان انگلیسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('en_ecat_title',null,array( "placeholder"=>"عنوان انگلیسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-1">عنوان روسی دسته بندی</label>
                        <div class="col-sm-9">
                            {{Form::text('ru_ecat_title',null,array( "placeholder"=>"عنوان روسی دسته بندی", "id"=>"form-field-1", "class"=>"form-control"))}}
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label"></label>
                        {{Form::submit('ذخیره اطلاعات',array('class'=>'btn btn-primary'))}}
                    </div>
                    {{Form::close()}}
                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>
    </div>
@stop
@section('script')
    @parent()

@stop()

app/views/backend/elearning_categories/index.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
@stop()

@section('content')
    <div class="col-sm-9">
        @if(Session::has('success'))
            <div class="alert alert-success ">
                <button data-dismiss="alert" class="close">×</button>
                <i class="fa fa-check-circle"></i>
                {{Session::get('success')}}
            </div>
        @endif()
        @if(Session::has('update'))
            <div class="alert alert-success ">
                <button data-dismiss="alert" class="close">×</button>
                <i class="fa fa-check-circle"></i>
                {{Session::get('update')}}
            </div>
        @endif()
    </div>
    <table class="table table-hover" id="sample-table-1">
        <thead>
        <tr>
            <th class="center">#</th>
            <th class="center">نام دسته بندی</th>
            <th class="hidden-xs center">عملیات</th>
            <th class="hidden-xs center">عملیات</th>
        </tr>
        </thead>
        <tbody>
        <?php $i = 1 ?>
        @foreach($elearningcategories as $c)
            <tr>
                <td class="center">{{$i}}</td>
                <td class="center">{{$c->fa_ecat_title}}</td>
                <td class="center">

                        {{Form::open(array('url'=>'admin/elearning_categories/'.$c->id))}}
                        {{Form::token()}}
                        {{Form::hidden('_method','DELETE')}}
                        {{Form::submit(' حذف ',array('class'=>'btn btn-xs btn-bricky ','style'=>'font-family:b nazanin; ','onclick'=>"if(!confirm('آیا مایل به تغییر وضعیت این ردیف هستید؟')){return false;};"))}}
                        {{Form::close()}}
                    </td>
                <td class="center"><a href="{{URL::route('admin.elearning_categories.edit',array($c->id))}}" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit">ویرایش</a></td>
            </tr><?php $i++ ?>
        @endforeach()
        </tbody>
    </table>
@stop

@section('script')
    @parent()
@stop()

app/views/backend/elearning_categories/show.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
@stop()

@section('content')

@stop

@section('script')
    @parent()
@stop()