app/routes.php
<?php
if (in_array(Request::segment(1), Config::get('app.alt_langs'))){
	App::setLocale(Request::segment(1));
	Session::set('la',App::getLocale());
	Config::set('app.locale_prefix', Request::segment(1));
}
$routes = Lang::get('routes');
foreach($routes as $k => $v){
	Route::pattern($k, $v);
}
$la = App::getLocale();
Route::group(array('prefix'=>Config::get('app.locale_prefix'),"before"=>'auth'),function(){
    /*************************************************************************/
    Route::get("/{customer_portal}","HomeController@datasheet");
    Route::post("/customer_portal/data",['as'=>'datasheet.data','uses'=>'HomeController@datasheet_search']);
});
Route::group(array('prefix' =>Config::get('app.locale_prefix')),function(){
	/*************************************************************************/
	Route::get("/{product}","HomeController@product");
	Route::get("/{product}/{title}","HomeController@product_page");
	/*************************************************************************/
	Route::get("/{projects}","HomeController@project");
	Route::get("/{projects}/{title}/","HomeController@project_page");
	/*************************************************************************/
	Route::get("/",['as'=>'home','uses'=>"HomeController@home"]);
	Route::get("/{about}","HomeController@about");
	/*************************************************************************/
	Route::get("/{learning}","HomeController@news");
    Route::get("/{learning}/{category}/{title}","HomeController@news_page");
    Route::get("/{learning}/{category}/","HomeController@news_cat");
    /*************************************************************************/
    Route::get("/{team}/{title}","HomeController@team");
	/*************************************************************************/
	Route::get("/{service}/{category}","HomeController@service");
	Route::get("/{service}/{category}/{title}","HomeController@service_page");

	/*************************************************************************/
    Route::get("/{contact}","HomeController@contact");
});
Route::group(array('prefix'=>"admin",'before'=>'auth'),function(){
	Route::get('dashboard',function(){
        $arr = array();
        foreach (Auth::user()->group as $gp){
            $arr[] = $gp->en_name;
        }
        $user_gp = $arr[0];
        if($user_gp == "admin"){
            return View::make('backend.index')->with('class_dashboard','class="open active"');
        }else{
            return Redirect::route('home');
        }
	});
	/*************************************************************************/
	Route::resource('teams', 'TeamsController');
	Route::resource('team_categories', 	'TeamCategoriesController');
	Route::resource('team_profession_categories', 'TeamProfessionCategoriesController');
	/*************************************************************************/
	Route::resource('menu','MenusController');
	/*************************************************************************/
	Route::resource('portfolio_categories', 'PortfolioCategoriesController');
	Route::resource('portfolios', 'PortfoliosController');
	/*************************************************************************/
	Route::resource('companies', 'CompaniesController');
	Route::resource('company_categories', 'CompanyCategoriesController');
	/*************************************************************************/
	Route::resource('elearnings', 'ElearningsController');
	Route::resource('elearning_categories', 'ElearningCategoriesController');
	Route::resource('medias', 'MediasController');
	/*************************************************************************/
	Route::resource('products', 'ProductsController');
	Route::resource('product_categories', 'ProductCategoriesController');
	/*************************************************************************/
	Route::resource('pages', 'PagesController');
	/*************************************************************************/
	Route::resource('datasheets', 'DatasheetsController');
	Route::resource('datasheet_codes', 'DatasheetCodesController');
	Route::resource('datasheet_companies', 'DatasheetCompaniesController');
	Route::resource('datasheet_project_types', 'DatasheetProjectTypesController');
	Route::resource('datasheet_customers', 'DatasheetCustomersController');
	/*************************************************************************/
	Route::resource('users', 'UserController');
	Route::resource('groups', 'GroupsController');
	/*************************************************************************/
	Route::resource('services', 'ServicesController');
	/*************************************************************************/
	Route::resource('service_categories', 'ServiceCategoriesController');
	Route::resource('settings', 'SettingsController');
	/*************************************************************************/
	Route::resource('sliders', 'SlidersController');
	Route::resource('portfolio_customers', 'PortfolioCustomersController');
});
Route::controller('password', 'RemindersController');
Route::get('login', array('as' => 'login', 'uses' => 'UserController@loginshow'));
Route::post('login', array('as' => 'login', 'uses' => 'UserController@authenticate'));
Route::get('logout', array('as' => 'logout', 'uses' => 'UserController@logout'));
Route::get('sitemap',function(){
    $portfolio = Portfolio::orderBy('created_at')->get();
    $learning = Elearning::orderBy('created_at')->get();
    $service = Service::orderBy('created_at')->get();
    $team = Team::orderBy('created_at')->get();
    $product = Product::orderBy('created_at')->get();
	$sitemap = App::make('sitemap');
    //$sitemap->setCache('laravel.sitemap', 3600);
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale()),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.product',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.certificate',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.mission_statement',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.organizational_value',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.customers',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
    foreach ($product as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($portfolio as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($learning as $l) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale()).'/'.$l->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($service as $s) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.service',array(),App::getLocale()).'/'.$s->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($team as $t) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.team',array(),App::getLocale()).'/'.$t->{App::getLocale().'_family'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }

    return $sitemap->render('xml');
});
App::missing(function(){
	return Response::view('layout.front.404',array('title'=>'not found'),404);
});

app/models/Elearning.php
<?php

class Elearning extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		 'fa_title' => 'required|max:50',
		 //'ru_title' => 'required|max:50',
		 //'en_title' => 'required|max:50',
		 'fa_body' => 'required',
		 //'en_body' => 'required',
		 //'ru_body' => 'required',

	];

	// Don't forget to fill this array
	protected $fillable = ['ru_body','ru_title','fa_title','en_title','fa_body','en_body'];

	public function category(){
		return $this->belongsToMany('ElearningCategory')->withPivot('elearning_category_id');
	}

}

app/controllers/ElearningsController.php
<?php
use Intervention\Image\ImageManagerStatic as Imagic;
use \Illuminate\Database\Eloquent\ModelNotFoundException;
class ElearningsController extends \BaseController {

	/**
	 * Display a listing of elearnings
	 *
	 * @return Response
	 */
	public function index()
	{
		$elearnings = Elearning::all();

		return View::make('backend.elearnings.index', array('elearnings'=>$elearnings))
		->with('title','کارگاه آموزشی')
        ->with('class_elearning',"class='open active'");
	}
	/**
	 * Show the form for creating a new elearning
	 *
	 * @return Response
	 */
	public function create()
	{
		$category = ElearningCategory::all();
		return View::make('backend.elearnings.create',array('category'=>$category))
		->with('title','ایجاد خبر')
        ->with('class_elearning',"class='open active'");
	}

	/**
	 * Store a newly created elearning in storage.
	 *
	 * @return Response
	 */
	public function store(){
		$validator = Validator::make($data = Input::all(), Elearning::$rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}
		if(Input::hasFile('file')) {
			$img1 = Input::file('file');
			$filename1 = $img1->getClientOriginalName();
			$path1 ="backend/assets/images/news/".$filename1;
			$width = Imagic::make($img1)->width();
			$height = Imagic::make($img1)->height();
            if($width == $height ){
                $image3 = Imagic::make($img1);
                $image3->resize(150,150);
                $image3->save(public_path($path1));
            }else{
                return Redirect::back()->withInput()->with('img','طول و عرض تصویر باهم برابر نیست');
            }
		}else{
			$path1 = "https://placeholdit.imgix.net/~text?txtsize=19&bg=efefef&txtclr=aaaaaa&txt=no+image&w=500&h=239&txttrack=0";
		}
		$learning = Elearning::create(
			array(
				'img'=>$path1,
				'fa_title'=>Input::get('fa_title'),
				'fa_body'=>Input::get('fa_body'),
				'en_body'=>Input::get('en_body'),
				'ru_body'=>Input::get('ru_body'),
				'en_title'=>Input::get('en_title'),
				'ru_title'=>Input::get('ru_title'),
			)
		);
		$id = $learning->id;
		$learning = new Elearning();
		$learning->find($id)->category()->attach(Input::get('category'));
		return Redirect::route('admin.elearnings.index')
			->with('success','اطلاعات جدید با موفقیت ذخیره شد')
			->with('title','لیست اخبار ')
			->with('class_elearning','class="active open"');
	}
	/**
	 * Display the specified elearning.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$elearning = Elearning::findOrFail($id);
		return View::make('backend.elearnings.show', compact('elearning'));
	}
	/**
	 * Show the form for editing the specified elearning.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$result_ecat=[];
		$elearning = Elearning::find($id);
		$category = ElearningCategory::all();
		$portfoliocategory = $elearning->category;
		foreach($portfoliocategory as $pcat){
			$result_ecat[]=$pcat->fa_ecat_title;
		}
		return View::make('backend.elearnings.edit', array('result_ecat'=>$result_ecat,'elearning'=>$elearning,'category'=>$category))
		->with('class_elearning',"class='open active'")
		->with('title',"ویرایش خبر");
	}
	/**
	 * Update the specified elearning in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$elearning = new Elearning();
		$e = $elearning->findOrFail($id);
		$validator = Validator::make($data = Input::all(), Elearning::$rules);
		if ($validator->fails()) {
			return Redirect::back()->withErrors($validator)->withInput();
		}
		if(Input::hasFile('file')){
			$img1 = Input::file('file');
            $width = Imagic::make($img1)->width();
            $height = Imagic::make($img1)->height();
			$filename_img1 = $img1->getClientOriginalName();
			$path1 ="backend/assets/images/news/".$filename_img1;
            if($width == $height ){
                $image3 = Imagic::make($img1);
                $image3->resize(150,150);
                $image3->save(public_path($path1));
                File::delete(array(public_path($elearning->img)));
            }
			$data['file'] = $path1;
		}
		else{
			$data['file']=$elearning->img1;
		}
		$e->img = $data['file'];
		$e->fa_title = Input::get('fa_title');
		$e->ru_title = Input::get('ru_title');
		$e->en_title = Input::get('en_title');
		$e->en_body = Input::get('en_body');
		$e->ru_body = Input::get('ru_body');
		$e->fa_body = Input::get('fa_body');
		$e->save();
		$e->category()->sync(Input::get('category'));
		return Redirect::route('admin.elearnings.index')
		->with('class_elearning',"class='open active'")
		->with('update','اطلاعات با موفقیت ویرایش شد');
	}
	/**
	 * Remove the specified elearning from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Elearning::destroy($id);
		return Redirect::route('admin.elearnings.index')
		->with('success','اطلاعات مورد نظر با موفقیت حذف شد')
		->with('class_elearning',"class='open active'")
		->with('title','لیست کارگاه آموزشی');
	}
}

app/views/backend/elearnings/create.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
    {{HTML::style('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css')}}
    {{HTML::script('backend/assets/plugins/ckeditor/ckeditor.js')}}
    {{HTML::style('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css')}}
@stop()
@section('content')
    <div class="col-sm-9">
        @if($errors->has())
            <div class="alert alert-danger ">
                <button data-dismiss="alert" class="close">×</button>
                @foreach($errors->all() as $errors)
                    <i class="fa fa-bug"></i>
                    {{$errors}}<br/>
                @endforeach()
            </div>
        @endif()
            @if(Session::has('img'))
                <div class="alert alert-warning ">
                    <button data-dismiss="alert" class="close">×</button>
                    <i class="fa fa-check-circle"></i>
                    {{Session::get('img')}}
                </div>
            @endif()
    </div>
    <div class="row">
        <div class="col-sm-12">
            <!-- start: TEXT FIELDS PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    {{Form::open(array('route'=>'admin.elearnings.store','method'=>'POST','class'=>'form-horizontal','role'=>'form','enctype'=>"multipart/form-data"))}}
                    <div class="tabbable">
                        <ul id="myTab" class="nav nav-tabs tab-bricky">
                            <li class="active">
                                <a href="#panel_tab2_example1" data-toggle="tab">
                                    <i class="green fa"></i> اطلاعات فارسی
                                </a>
                            </li>
                            <li class="">
                                <a href="#panel_tab2_example2" data-toggle="tab">اطلاعات انگلیسی</a>
                            </li>
                            <li class="">
                                <a href="#panel_tab3_example2" data-toggle="tab">اطلاعات روسی</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="panel_tab2_example1">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان فارسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('fa_title','',array( "placeholder"=>"عنوان فارسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن فارسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('fa_body','',array( "placeholder"=>"متن فارسی", "id"=>"ee", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="panel_tab2_example2">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان انگلیسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('en_title','',array( "placeholder"=>"عنوان انگلیسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن انگلیسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('en_body','',array( "placeholder"=>"متن انگلیسی", "id"=>"rr", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="panel_tab3_example2">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان روسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('ru_title','',array( "placeholder"=>"عنوان روسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن روسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('ru_body','',array( "placeholder"=>"متن روسی", "id"=>"aa", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label"> تصویر خبر </label>
                        <div class="col-sm-9">
                            <div class="fileupload fileupload-new" data-provides="fileupload"><input type="hidden" value="" name="">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA?text=no+image" alt="">
                                </div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 10px;"></div>
                                <div>
                                    <span class="btn btn-light-grey btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> انتخاب تصویر</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> ویرایش تصویر</span>
                                        <input type="file" name="file" title="file">
                                    </span>
                                    <a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
                                        <i class="fa fa-times"></i> حذف
                                    </a>
                                </div>
                            </div>
                            <div class="alert alert-warning">
                                <span class="label label-warning">تذکر</span>
                                <span>تصویر را دقیقا اندازه  500x239 انتخاب کنید</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-select-4">دسته بندی</label>
                        <div class="col-sm-9">
                            <select name="category[]" class="form-control js-example-basic-multiple" id="form-field-select-4" multiple="multiple">
                                @foreach($category as $cat)
                                    <option value="{{$cat->id}}">{{$cat->fa_ecat_title}}</option>
                                @endforeach()
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label"></label>
                        {{Form::submit('ذخیره اطلاعات',array('class'=>'btn btn-primary'))}}
                    </div>
                    {{Form::close()}}
                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>
    </div>
@stop
@section('script')
    @parent()
    {{HTML::script('backend/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')}}
    {{HTML::script('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js')}}
    {{HTML::script('backend/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js')}}
    {{HTML::script('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js')}}
    <script type="text/javascript">
        $('.js-example-basic-multiple').select2();
        CKEDITOR.editorConfig = function( config ) {
            config.toolbarGroups = [
                { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
                { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
                { name: 'links', groups: [ 'links' ] },
                { name: 'insert', groups: [ 'insert' ] },
                { name: 'forms', groups: [ 'forms' ] },
                { name: 'tools', groups: [ 'tools' ] },
                { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
                { name: 'others', groups: [ 'others' ] },
                { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
                { name: 'colors', groups: [ 'colors' ] },
                { name: 'styles', groups: [ 'styles' ] },
                { name: 'about', groups: [ 'about' ] }
            ];

            config.removeButtons = 'Underline,Subscript,Superscript';
        };
           CKEDITOR.replace('ee');
            CKEDITOR.replace('rr');
            CKEDITOR.replace('aa');
    </script>
@stop()

app/views/backend/elearnings/index.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
    {{HTML::style('//cdn.datatables.net/1.10.7/css/jquery.dataTables.css')}}
@stop()
@section('content')
    <div class="col-sm-9">
        @if(Session::has('success'))
            <div class="alert alert-success ">
                <button data-dismiss="alert" class="close">×</button>
                <i class="fa fa-check-circle"></i>
                {{Session::get('success')}}
            </div>
        @endif()
        @if(Session::has('update'))
            <div class="alert alert-success ">
                <button data-dismiss="alert" class="close">×</button>
                <i class="fa fa-check-circle"></i>
                {{Session::get('update')}}
            </div>
        @endif()
    </div>
    <div class="table-responsive">
    <table id="sample-table-1" class="table table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th class="center">عنوان</th>
            <th class="center">دسته بندی</th>
            <th class="center">وبرایش</th>
            <th class="center">حذف</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th class="center">عنوان</th>
            <th class="center">دسته بندی</th>
            <th class="center">وبرایش</th>
            <th class="center">حذف</th>
        </tr>
        </tfoot>
        <tbody>
        @foreach($elearnings as $e)
            <tr>
                <td class="center "><b>{{$e->fa_title}}</b></td>
                <td class="center ">
                @foreach ($e->category as $cat)
                    {{$cat->fa_ecat_title}} -
                  @endforeach()</td>
                <td class="center">
                    <a href="{{URL::route('admin.elearnings.edit',array($e->id))}}" class="btn btn-xs btn-teal tooltips" data-placement="top" >ویرایش</a>
                </td>
                <td>
                    {{Form::open(array('url'=>'admin/elearnings/'.$e->id))}}
                    {{Form::token()}}
                    {{Form::hidden('_method','DELETE')}}
                    {{Form::submit(' حذف ',array('class'=>'btn btn-xs btn-bricky ','style'=>'font-family:b nazanin; ','onclick'=>"if(!confirm('آیا مایل به تغییر وضعیت این ردیف هستید؟')){return false;};"))}}
                    {{Form::close()}}
                </td>
            </tr>
        @endforeach()
        </tbody>
    </table>
    </div>
@stop
@section('script')
    @parent()
    {{HTML::script('//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js')}}
    <script>
        $(document).ready(function() {
            $('#example').dataTable( {
                "scrollY":        "800px",
                "scrollCollapse": true
            } );
        } );
    </script>
@stop()

app/views/backend/elearnings/show.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
@stop()

@section('content')

@stop

@section('script')
    @parent()
@stop()