app/routes.php
<?php
if (in_array(Request::segment(1), Config::get('app.alt_langs'))){
	App::setLocale(Request::segment(1));
	Session::set('la',App::getLocale());
	Config::set('app.locale_prefix', Request::segment(1));
}
$routes = Lang::get('routes');
foreach($routes as $k => $v){
	Route::pattern($k, $v);
}
$la = App::getLocale();
Route::group(array('prefix'=>Config::get('app.locale_prefix'),"before"=>'auth'),function(){
    /*************************************************************************/
    Route::get("/{customer_portal}","HomeController@datasheet");
    Route::post("/customer_portal/data",['as'=>'datasheet.data','uses'=>'HomeController@datasheet_search']);
});
Route::group(array('prefix' =>Config::get('app.locale_prefix')),function(){
	/*************************************************************************/
	Route::get("/{product}","HomeController@product");
	Route::get("/{product}/{title}","HomeController@product_page");
	/*************************************************************************/
	Route::get("/{projects}","HomeController@project");
	Route::get("/{projects}/{title}/","HomeController@project_page");
	/*************************************************************************/
	Route::get("/",['as'=>'home','uses'=>"HomeController@home"]);
	Route::get("/{about}","HomeController@about");
	/*************************************************************************/
	Route::get("/{learning}","HomeController@news");
    Route::get("/{learning}/{category}/{title}","HomeController@news_page");
    Route::get("/{learning}/{category}/","HomeController@news_cat");
    /*************************************************************************/
    Route::get("/{team}/{title}","HomeController@team");
	/*************************************************************************/
	Route::get("/{service}/{category}","HomeController@service");
	Route::get("/{service}/{category}/{title}","HomeController@service_page");

	/*************************************************************************/
    Route::get("/{contact}","HomeController@contact");
});
Route::group(array('prefix'=>"admin",'before'=>'auth'),function(){
	Route::get('dashboard',function(){
        $arr = array();
        foreach (Auth::user()->group as $gp){
            $arr[] = $gp->en_name;
        }
        $user_gp = $arr[0];
        if($user_gp == "admin"){
            return View::make('backend.index')->with('class_dashboard','class="open active"');
        }else{
            return Redirect::route('home');
        }
	});
	/*************************************************************************/
	Route::resource('teams', 'TeamsController');
	Route::resource('team_categories', 	'TeamCategoriesController');
	Route::resource('team_profession_categories', 'TeamProfessionCategoriesController');
	/*************************************************************************/
	Route::resource('menu','MenusController');
	/*************************************************************************/
	Route::resource('portfolio_categories', 'PortfolioCategoriesController');
	Route::resource('portfolios', 'PortfoliosController');
	/*************************************************************************/
	Route::resource('companies', 'CompaniesController');
	Route::resource('company_categories', 'CompanyCategoriesController');
	/*************************************************************************/
	Route::resource('elearnings', 'ElearningsController');
	Route::resource('elearning_categories', 'ElearningCategoriesController');
	Route::resource('medias', 'MediasController');
	/*************************************************************************/
	Route::resource('products', 'ProductsController');
	Route::resource('product_categories', 'ProductCategoriesController');
	/*************************************************************************/
	Route::resource('pages', 'PagesController');
	/*************************************************************************/
	Route::resource('datasheets', 'DatasheetsController');
	Route::resource('datasheet_codes', 'DatasheetCodesController');
	Route::resource('datasheet_companies', 'DatasheetCompaniesController');
	Route::resource('datasheet_project_types', 'DatasheetProjectTypesController');
	Route::resource('datasheet_customers', 'DatasheetCustomersController');
	/*************************************************************************/
	Route::resource('users', 'UserController');
	Route::resource('groups', 'GroupsController');
	/*************************************************************************/
	Route::resource('services', 'ServicesController');
	/*************************************************************************/
	Route::resource('service_categories', 'ServiceCategoriesController');
	Route::resource('settings', 'SettingsController');
	/*************************************************************************/
	Route::resource('sliders', 'SlidersController');
	Route::resource('portfolio_customers', 'PortfolioCustomersController');
});
Route::controller('password', 'RemindersController');
Route::get('login', array('as' => 'login', 'uses' => 'UserController@loginshow'));
Route::post('login', array('as' => 'login', 'uses' => 'UserController@authenticate'));
Route::get('logout', array('as' => 'logout', 'uses' => 'UserController@logout'));
Route::get('sitemap',function(){
    $portfolio = Portfolio::orderBy('created_at')->get();
    $learning = Elearning::orderBy('created_at')->get();
    $service = Service::orderBy('created_at')->get();
    $team = Team::orderBy('created_at')->get();
    $product = Product::orderBy('created_at')->get();
	$sitemap = App::make('sitemap');
    //$sitemap->setCache('laravel.sitemap', 3600);
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale()),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.product',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.about',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.certificate',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.mission_statement',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.organizational_value',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
	$sitemap->add(url('/'.App::getLocale().'/'.Lang::get('routes.customers',array(),App::getLocale())),date("Y-m-d"),'weekly','0.8');
    foreach ($product as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($portfolio as $p) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.projects',array(),App::getLocale()).'/'.$p->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'

        );
    }
    foreach ($learning as $l) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.learning',array(),App::getLocale()).'/'.$l->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($service as $s) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.service',array(),App::getLocale()).'/'.$s->{App::getLocale().'_title'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }
    foreach ($team as $t) {
        $sitemap->add(
            url('/'.App::getLocale().'/'.Lang::get('routes.team',array(),App::getLocale()).'/'.$t->{App::getLocale().'_family'} ),
            date("Y-m-d"),
            'weekly',
            '0.3'
        );
    }

    return $sitemap->render('xml');
});
App::missing(function(){
	return Response::view('layout.front.404',array('title'=>'not found'),404);
});

app/models/Product.php
<?php

class Product extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		 'fa_title' => 'required',
		 //'en_title' => 'required',
		 //'ru_title' => 'required',
		'fa_description'=>'required',
		//'en_description'=>'required',
		//'ru_description'=>'required',

	];

	// Don't forget to fill this array
	protected $fillable = ['ru_description','ru_title','fa_title','fa_description','en_title','en_description'];
	public function category(){
		return $this->belongsToMany('ProductCategory');
	}
}

app/controllers/ProductsController.php
<?php
use Intervention\Image\ImageManagerStatic as Imagic;
use \Illuminate\Database\Eloquent\ModelNotFoundException;
class ProductsController extends \BaseController {

	/**
	 * Display a listing of products
	 *
	 * @return Response
	 */
	public function index()
	{
		$products = Product::all();
		return View::make('backend.products.index', compact('products'))
		->with('title','لیست محصولات')
        ->with('class_product',"class='open active'");
	}

	/**
	 * Show the form for creating a new product
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('backend.products.create')
		->with('menus', ProductCategoriesController::categoryFullArray())
		->with('title','ایجاد محصول')
        ->with('class_product',"class='open active'")
		->with('info_product',"<div class='alert alert-block alert-info fade in'><button data-dismiss='alert' class='close'' type='button''>×</button>
										<h3 class='alert-heading'><i class='fa fa-info-circle'></i> راهنمایی  </h3>
										<h4><p>کاربر گرامی در نظر داشته باشید برای انتخاب دسته بندی ها چنانچه زیر دسته است ، دسته پدر و یا پدرانش را هم انتخاب کنید</p></h4></div>");
	}

	/**
	 * Store a newly created product in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$product = new Product();
		$validator = Validator::make($data = Input::all(), Product::$rules);
		if ($validator->fails()){
			return Redirect::back()->withErrors($validator)->withInput();
		}
		if(Input::hasFile('file')){
			$imagefile3 = Input::file('file');
			$filename3 = $imagefile3->getClientOriginalName();
			$width3 = Imagic::make($imagefile3)->width();
			$height3 = Imagic::make($imagefile3)->height();
			$image3 = Imagic::make($imagefile3);
            $lens = $width3 - $height3;
			if(($width3 == $height3) or ($height3 > $width3)){
				return Redirect::back()->withInput()->with('img','تصویر سوم یا پرتره است یا طول و عرضش برابرست');
			}elseif($lens >= 200){
				$path1 ="backend/assets/images/portfolio/".$filename3;
				$image3->save(public_path($path1));
			}
		}
		else{
			$path1 = "https://placeholdit.imgix.net/~text?txtsize=19&bg=efefef&txtclr=aaaaaa&txt=no+image&w=1920&h=900&txttrack=0";
		}

		$product_id=Product::create(array(
			'img'=>$path1,
			'fa_title'=>Input::get('fa_title'),
			'ru_title'=>Input::get('fa_title'),
			'en_title'=>Input::get('en_title'),
			'fa_description'=>Input::get('fa_description'),
			'ru_description'=>Input::get('fa_description'),
			'en_description'=>Input::get('en_description'),
		));
		$id = $product_id->id;
		$product->find($id)->category()->attach(Input::get('category'));
		return Redirect::route('admin.products.index')
			->with('success','اطلاعات جدید با موفقیت ذخیره شد')
			->with('title','لیست محصولات')
			->with('class_product','class="active open"');
	}

	/**
	 * Display the specified product.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		try{
			$product = Product::findOrFail($id);
			return View::make('backend.products.show', compact('product'));
		}catch (ModelNotFoundException $e){
			return Redirect::route('admin.products.index');
		}
	}

	/**
	 * Show the form for editing the specified product.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		try{
			$product = Product::find($id);
			$pcat = $product->category;
			return View::make('backend.products.edit', array('product'=>$product, 'pcat'=>$pcat))
				->with('class_product',"class='open active'")
				->with('menus', ProductCategoriesController::categoryFullArray())
				->with('info_product_edit',"<div class='alert alert-block alert-info fade in'><button data-dismiss='alert' class='close'' type='button''>×</button><h3 class='alert-heading'><i class='fa fa-info-circle'></i> راهنمایی  </h3>
										<h4><p>کاربر گرامی اگر مایل به تغییر دسته بندی محصول هستید دسته بندی جدید را وارد کنید سیستم به صورت اتوماتیک دسته بندی های قبلی را حذف خواهد کرد</p></h4></div>")
				->with('title',"ویرایش محصول");
		}catch (ModelNotFoundException $e){
			return Redirect::route('admin.products.index');
		}
	}

	/**
	 * Update the specified product in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$product =  Product::findOrFail($id);
		$validator = Validator::make($data = Input::all(), Product::$rules);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}
		if(Input::hasFile('file')){
			$img1 = Input::file('file');
			$filename_img1 = $img1->getClientOriginalName();
			$path1 ="backend/assets/images/products/".$filename_img1;
			File::delete(array(public_path($product->img)));
			Imagic::make($img1->getRealPath())->save(public_path($path1));
			$data['file'] = $path1;
		}
		else{
			$data['file']=$product->img1;
		}
		$product->img=$data['file'];
		$product->fa_title=Input::get('fa_title');
		$product->ru_title=Input::get('ru_title');
		$product->en_title=Input::get('en_title');
		$product->fa_description=Input::get('fa_description');
		$product->ru_description=Input::get('ru_description');
		$product->en_description=Input::get('en_description');
		$product->save();
		if(array_key_exists('category',$data)) {
			$product->find($id)->category()->sync(Input::get('category'));
		}
		return Redirect::route('admin.products.index')
		->with('class_product',"class='open active'")
		->with('update','اطلاعات با موفقیت ویرایش شد');
	}
	/**
	 * Remove the specified product from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Product::destroy($id);
		return Redirect::route('admin.products.index')
		->with('success','اطلاعات مورد نظر با موفقیت حذف شد')
		->with('class_product',"class='open active'");
	}
}

app/views/backend/products/create.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
    {{HTML::style('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css')}}
    {{HTML::style('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css')}}
@stop()
@section('content')
    <div class="col-sm-9">
        @if($errors->has())
            <div class="alert alert-danger ">
                <button data-dismiss="alert" class="close">×</button>
                @foreach($errors->all() as $errors)
                    <i class="fa fa-bug"></i>
                    {{$errors}}<br/>
                @endforeach()
            </div>
        @endif()
    </div>
    <div class="row">
        <div class="col-sm-12">
            <!-- start: TEXT FIELDS PANEL -->
            <div class="panel panel-default">
                <div class="panel-body">
                    {{Form::open(array('route'=>'admin.products.store','method'=>'POST','class'=>'form-horizontal','role'=>'form','enctype'=>"multipart/form-data"))}}
                    {{Form::token()}}
                    <div class="tabbable">
                        <ul id="myTab" class="nav nav-tabs tab-bricky">
                            <li class="active">
                                <a href="#panel_tab2_example1" data-toggle="tab">
                                    <i class="green fa"></i> اطلاعات فارسی
                                </a>
                            </li>
                            <li class="">
                                <a href="#panel_tab2_example2" data-toggle="tab">اطلاعات انگلیسی</a>
                            </li>
                            <li class="">
                                <a href="#panel_tab3_example2" data-toggle="tab">اطلاعات روسی</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="panel_tab2_example1">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان محصول فارسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('fa_title','',array( "placeholder"=>"عنوان محصول فارسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن فارسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('fa_description','',array( "placeholder"=>"متن فارسی", "id"=>"ee", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="panel_tab2_example2">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان محصول انگلیسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('en_title','',array( "placeholder"=>"عنوان محصول انگلیسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن انگلیسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('en_description','',array( "placeholder"=>"متن انگلیسی", "id"=>"rr", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="panel_tab3_example2">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">عنوان محصول روسی</label>
                                    <div class="col-sm-9">
                                        {{Form::text('ru_title','',array( "placeholder"=>"عنوان محصول روسی", "id"=>"form-field-1", "class"=>"form-control"))}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label" for="form-field-1">متن روسی</label>
                                    <div class="col-sm-9">
                                        {{Form::textarea('ru_description','',array( "placeholder"=>"متن روسی", "id"=>"aa", "class"=>" form-control"))}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label"> تصویر محصول </label>
                        <div class="col-sm-9">
                            <div class="fileupload fileupload-new" data-provides="fileupload"><input type="hidden" value="" name="">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA?text=no+image" alt="">
                                </div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 10px;"></div>
                                <div>
                                    <span class="btn btn-light-grey btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> انتخاب تصویر</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> ویرایش تصویر</span>
                                        <input type="file" name="file" title="file">
                                    </span>
                                    <a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
                                        <i class="fa fa-times"></i> حذف
                                    </a>
                                </div>
                            </div>
                            <div class="alert alert-warning">
                                <span class="label label-warning">تذکر</span>
                                <span>اندازه تصویر محصول حتما 1920x900 انتخاب کنید</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="form-field-select-4">دسته بندی</label>
                        <div class="col-sm-9">
                        <div class="panel-scroll" >
                            <div class="col-sm-12">
                                <?php $dash='';?>
                                @if(count($menus) > 0)
                                    <ul>
                                        @foreach($menus as $menu)
                                            @include('backend.products.list',array('menu'=>$menu,'dash'=>$dash))
                                        @endforeach
                                    </ul>
                                @else
                                    {{ "دسته بندی یافت نشد" }}
                                @endif
                            </div> <!-- /.col -->
                        </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label"></label>
                        {{Form::submit('ذخیره اطلاعات',array('class'=>'btn btn-primary'))}}
                    </div>
                    {{Form::close()}}
                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>
    </div>
@stop
@section('script')
    @parent()
    {{HTML::script('backend/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')}}
    {{HTML::script('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js')}}
    {{HTML::script('backend/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js')}}
    {{HTML::script('backend/assets/plugins/ckeditor/ckeditor.js')}}
    {{HTML::script('backend/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js')}}
    <script type="text/javascript">
        $('.js-example-basic-multiple').select2();
        CKEDITOR.replace('ee');
        CKEDITOR.replace('rr');
        CKEDITOR.replace('aa');
    </script>
@stop()

app/views/backend/products/index.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
    {{HTML::style('//cdn.datatables.net/1.10.7/css/jquery.dataTables.css')}}
@stop()
@section('content')
    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
        <thead>
        <tr>
            <th class="center">نام محصول</th>
            <th  class="center">دسته بندی</th>
            <th  class="center">توضیحات</th>
            <th  class="center">ویرایش</th>
            <th  class="center">حذف</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $p)
        <tr>
            <td>{{$p->fa_title}}</td>
            <td class="hidden-xs">@foreach($p->category as $cat){{$cat->fa_name}} - @endforeach()</td>
            <td>{{str_limit($p->fa_description,20,'...')}}</td>
            <td class="center">
                <a href="{{URL::route('admin.products.edit',array($p->id))}}" class="btn btn-xs btn-teal tooltips" data-placement="top" >ویرایش</a>
            </td>
            <td>
                {{Form::open(array('url'=>'admin/products/'.$p->id))}}
                {{Form::token()}}
                {{Form::hidden('_method','DELETE')}}
                {{Form::submit(' حذف ',array('class'=>'btn btn-xs btn-bricky ','style'=>'font-family:b nazanin; ','onclick'=>"if(!confirm('آیا مایل به تغییر وضعیت این ردیف هستید؟')){return false;};"))}}
                {{Form::close()}}
            </td>
        </tr>
            @endforeach()
        </tbody>
    </table>
@stop
@section('script')
    @parent()
        {{HTML::script('//cdn.datatables.net/1.10.7/js/jquery.dataTables.js')}}
        {{HTML::script('//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js')}}
    <script>
        $(document).ready(function() {
            $('#sample_1').DataTable();
        } );
    </script>
@stop()

app/views/backend/products/list.blade.php
    <?php
        $class='';
        if(!$menu['active']){
        $class = "style='color: red'";
        }else{
            $class = "style='color: blue'";
        }
    ?>
   <li style="list-style:none">
       <div class="checkbox">
           <label>
               <input type="checkbox" value="{{$menu['id']}}" name="category[]" class="square-grey">
               {{$menu['fa_name']}}
           </label>
       </div>
   </li>
       @if(count($menu['child']) > 0)
    <?php  $dash.=' ';?>
    <ul>
        @foreach($menu['child'] as $menu)
                @include('backend.products.list', $menu)
        @endforeach
    </ul>
       @endif

app/views/backend/products/list_edit.blade.php
<?php
    $class='';
    if(!$menu['active']){
    $class = "style='color: red'";
    }else{
        $class = "style='color: blue'";
    }
?>
<li style="list-style:none">
   <div class="checkbox">
       <label>
           <input type="checkbox" value="{{$menu['id']}}" name="category[]" class="square-grey">
           {{$menu['fa_name']}}
       </label>
   </div>
</li>
   @if(count($menu['child']) > 0)
    <?php  $dash.=' ';?>
    <ul>
        @foreach($menu['child'] as $menu)
            @include('backend.products.list_edit', $menu)
        @endforeach
    </ul>
   @endif

app/views/backend/products/list_edit_check.blade.php
    <?php
        $class='';
        if(!$menu['active']){
        $class = "style='color: red'";
        }else{
            $class = "style='color: blue'";
        }
    ?>
   <li style="list-style:none">
       <div class="checkbox">
           <label>
               @foreach($pcat as $cat)
                       <input type="checkbox" value="{{$menu['id']}}" name="category[]" checked class="square-grey">
                       {{$menu['fa_name']}}
               @endforeach()
           </label>
       </div>
   </li>
       @if(count($menu['child']) > 0)
    <?php  $dash.=' ';?>
    <ul>
        @foreach($menu['child'] as $menu)
                @include('backend.products.list_edit', $menu)
        @endforeach
    </ul>
       @endif

app/views/backend/products/show.blade.php
@extends("layout.admin_index")
@section('style')
    @parent
@stop()

@section('content')

@stop

@section('script')
    @parent()
@stop()